### ISSUE TITLE
Manter o id do usuário no tutorial e chamado

### ISSUE THREAD

**Issue by EnneLu** [Pas0quit0/Colab#16]

**Comment by EnneLu** [comment]
Usar issues

**Comment by marcos-arthur** [comment]
isso dai é em respeito ao banco?

**Comment by marcos-arthur** [comment]
id do usúario que enviou o tutorial agora é registrado

**Comment by marcos-arthur** [comment]
id do usuario e do laboratório aparecem quando se visualiza um chamado

**Comment by marcos-arthur** [comment]
Nome do usuário e do laboratório aparecem no lugar do id.

FECHADO. PRAW

**Comment by marcos-arthur** [comment]
UM MOMENTO!!

Ainda falta mostrar o nome do usuário no tutorial

**Comment by marcos-arthur** [comment]
Agora sim

FECHADO
